# Generated by Django 4.1.2 on 2022-10-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("lastname", models.CharField(blank=True, max_length=20)),
                ("mobile_number", models.PositiveIntegerField(max_length=10)),
                ("email", models.EmailField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_balance", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
