# Generated by Django 4.1.2 on 2022-10-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MailService", "0002_recommendations_transactionsdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountholder",
            name="mobile_number",
            field=models.IntegerField(max_length=10),
        ),
    ]
