# Generated by Django 4.1.2 on 2022-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MailService", "0003_alter_accountholder_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountholder",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="accountholder",
            name="mobile_number",
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
