# Generated by Django 4.1.2 on 2022-10-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MailService", "0006_alter_transactionsdetails_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionsdetails",
            options={},
        ),
    ]
