# Generated by Django 4.1.2 on 2022-10-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MailService", "0007_alter_transactionsdetails_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendations",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
